### ISSUE TITLE
Install Issue: funlib.segment wheels

### ISSUE THREAD

**Issue by cwulf1314** [kirchhausenlab/gc_segment#1]
I have been following the ReadMe instructions for install and ran into an issue on the last step. I get an error message that says wheels for funlib.segment could not be built, which is required for pyproject.toml-based projects. There is another error message above that says fatal error C1083: Cannot open include file: 'boost/pending/disjoint_sets.hpp': No such file or directory. I have tried searching for solutions and haven't found anything that works. I made sure that Microsoft Visual Studio BuildTools is installed, which fixed previous errors, but there seems to be something wrong with accessing the boost library, and I don't know how to fix it. Any advice is appreciated. Thank you.

**Comment by patrickstock** [comment]
This issue is caused by the `conda install -c conda-forge boost` step not installing the complete `boost` library. I have added a step to README.md with an `apt-get` install for Ubuntu (Step 4). 

Mac users can accomplish this with `brew` and Windows users can accomplish this by manual download and install from boost.org.
